unstable_features = true

comment_width                  = 120
max_width                      = 120
fn_single_line                 = true
single_line_let_else_max_width = 120
single_line_if_else_max_width  = 120
use_small_heuristics           = "Max"

format_code_in_doc_comments = true
imports_granularity         = "Crate"
wrap_comments               = true
