[package]
name    = "echos_assets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy               = { workspace = true }
bevy_common_assets = { workspace = true }
bevy_asset_loader  = { workspace = true }

serde    = { workspace = true }
fastrand = { workspace = true }
