file_logging_enabled = true
log_file_path        = "logs"
max_log_file_size    = 10485760
max_log_files        = 5
console_timestamps   = true
console_colors       = true

[categories]
Combat           = false
StateTransitions = false
Input            = false
Rendering        = false
Performance      = false
World            = false
Turns            = true
General          = false
AI               = true
